version: "4.0"
services:
  web:
    build: .
    ports:
      - "8100:5100"
    volumes:
      - /home/ryzen/Nao-MD:/code
      - /home/ryzen/Nao-MD/node_modules:/code/node_modules
      - logvolume01:/var/log
    links:
      - redis
  redis:
    image: redis
volumes:
  logvolume01: {}